#!/usr/bin/env bash
###############################################################################
# This script is the command that is executed every run.
# Check the examples in examples/
#
# This script is run in the execution directory (execDir, --exec-dir).
#
# PARAMETERS:
# $1 is the candidate configuration number
# $2 is the instance ID
# $3 is the seed
# $4 is the instance name
# The rest ($* after `shift 4') are parameters to the run
#
# RETURN VALUE:
# This script should print one numerical value: the cost that must be minimized.
# Exit with 0 if no error, with 1 in case of error
###############################################################################
## Find our own location.
# BINDIR=$(dirname "$(readlink -f "$(type -P $0 || echo $0)")")

error() {
	echo "$(TZ=UTC date): $0: error: $@"
	exit 1
}

# This parses the arguments given by irace. Do not touch it!
CONFIG_ID=$1
INSTANCE_ID=$2
SEED=$3
INSTANCE=$4
shift 4 || error "Not enough parameters"
CONFIG_PARAMS=$*
# End of parsing

EXE=../../bins/memetic/$INSTANCE_ID
EXE_PARAMS="${CONFIG_PARAMS}"

if [ ! -x "$(command -v ${EXE})" ]; then
	error "${EXE}: not found or not executable (pwd: $(pwd))"
fi

STDERR=/tmp/c${CONFIG_ID}-${INSTANCE_ID}-${SEED}.stderr

$EXE ${EXE_PARAMS}

exit 0
